version: "3.9"

services:
  db:
    container_name: fastapi-boilerplate_postgres_db
    image: postgres:15
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: fastapi-boilerplate
    image: fastapi-boilerplate:1.0.0

    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  migrate:
    container_name: fastapi-boilerplate_app_migrate
    image: fastapi-boilerplate:1.0.0
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./:/app
    command: alembic upgrade head

volumes:
  postgres_data: